@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddGradeCommandParser" as AddGradeCommandParser LOGIC_COLOR
participant "cmd:AddGradeCommand" as AddGradeCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
participant ":GradeCommandValidator" as GradeCommandValidator LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("addgrade c/CS2103T id/A1234567T as/1 g/85")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("addgrade c/CS2103T id/A1234567T as/1 g/85")
activate AddressBookParser

create AddGradeCommandParser
AddressBookParser -> AddGradeCommandParser
activate AddGradeCommandParser

AddGradeCommandParser --> AddressBookParser
deactivate AddGradeCommandParser

AddressBookParser -> AddGradeCommandParser : parse("c/CS2103T id/A1234567T as/1 g/85")
activate AddGradeCommandParser

create AddGradeCommand
AddGradeCommandParser -> AddGradeCommand
activate AddGradeCommand

AddGradeCommand --> AddGradeCommandParser
deactivate AddGradeCommand

AddGradeCommandParser --> AddressBookParser : cmd
deactivate AddGradeCommandParser
AddGradeCommandParser -[hidden]-> AddressBookParser

AddressBookParser --> LogicManager : cmd
deactivate AddressBookParser

LogicManager -> AddGradeCommand : execute(m)
activate AddGradeCommand

AddGradeCommand -> GradeCommandValidator : validateAndGetAssessment(m, courseCode, studentId, assessmentIndex)
activate GradeCommandValidator

GradeCommandValidator -> Model : hasCourse(courseCode)
activate Model
Model --> GradeCommandValidator : courseExists
deactivate Model

GradeCommandValidator -> Model : isStudentEnrolled(courseCode, studentId)
activate Model
Model --> GradeCommandValidator : isEnrolled
deactivate Model

GradeCommandValidator -> Model : getAssessmentForCourseByIndex(courseCode, assessmentIndex)
activate Model
Model --> GradeCommandValidator : assessment
deactivate Model

GradeCommandValidator --> AddGradeCommand : assessment
deactivate GradeCommandValidator

AddGradeCommand -> AddGradeCommand : check score <= assessment.maxScore

AddGradeCommand -> Model : hasGrade(toAdd)
activate Model
Model --> AddGradeCommand : hasDuplicate
deactivate Model

AddGradeCommand -> Model : addGrade(toAdd)
activate Model
Model --> AddGradeCommand
deactivate Model

AddGradeCommand -> Model : showGradesForCourse(courseCode)
activate Model
Model --> AddGradeCommand
deactivate Model

AddGradeCommand -> Model : setDisplayMode(GRADES)
activate Model
Model --> AddGradeCommand
deactivate Model

create CommandResult
AddGradeCommand -> CommandResult
activate CommandResult
CommandResult --> AddGradeCommand
deactivate CommandResult

AddGradeCommand --> LogicManager : r
deactivate AddGradeCommand

[<--LogicManager
deactivate LogicManager
@enduml
