@startuml
!include style.puml
skinparam ArrowFontStyle plain

actor User as user USER_COLOR
participant ":UI" as ui UI_COLOR
participant ":Logic" as logic LOGIC_COLOR
participant ":Model" as model MODEL_COLOR
participant ":Storage" as storage STORAGE_COLOR

user -[USER_COLOR]> ui : "removecourse c/CS2103"
activate ui UI_COLOR

ui -[UI_COLOR]> logic : execute("removecourse c/CS2103")
activate logic LOGIC_COLOR

logic -[LOGIC_COLOR]> model : update data for deletion
activate model MODEL_COLOR
model --[MODEL_COLOR]> logic
deactivate model

logic -[LOGIC_COLOR]> storage : saveAddressBook(addressBook)
activate storage STORAGE_COLOR
storage --[STORAGE_COLOR]> logic
deactivate storage

logic --[LOGIC_COLOR]> ui : CommandResult
deactivate logic

ui --[UI_COLOR]> user : display result
deactivate ui
@enduml
