@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":RemoveAssessmentCommandParser" as RemoveAssessmentCommandParser LOGIC_COLOR
participant "cmd:RemoveAssessmentCommand" as RemoveAssessmentCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("removeassessment c/CS2103T as/1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("removeassessment c/CS2103T as/1")
activate AddressBookParser

create RemoveAssessmentCommandParser
AddressBookParser -> RemoveAssessmentCommandParser
activate RemoveAssessmentCommandParser

RemoveAssessmentCommandParser --> AddressBookParser
deactivate RemoveAssessmentCommandParser

AddressBookParser -> RemoveAssessmentCommandParser : parse("c/CS2103T as/1")
activate RemoveAssessmentCommandParser

create RemoveAssessmentCommand
RemoveAssessmentCommandParser -> RemoveAssessmentCommand
activate RemoveAssessmentCommand

RemoveAssessmentCommand --> RemoveAssessmentCommandParser
deactivate RemoveAssessmentCommand

RemoveAssessmentCommandParser --> AddressBookParser : cmd
deactivate RemoveAssessmentCommandParser

AddressBookParser --> LogicManager : cmd
deactivate AddressBookParser

LogicManager -> RemoveAssessmentCommand : execute(m)
activate RemoveAssessmentCommand

RemoveAssessmentCommand -> Model : getAssessmentsForCourseInDisplayOrder(courseCode)
activate Model
Model --> RemoveAssessmentCommand : filteredAssessments
deactivate Model

alt filteredAssessments is empty
    RemoveAssessmentCommand --> LogicManager : throws CommandException
else assessment index is invalid
    RemoveAssessmentCommand --> LogicManager : throws CommandException
else assessment can be removed
    RemoveAssessmentCommand -> Model : removeAssessment(assessmentToRemove)
    activate Model
    Model --> RemoveAssessmentCommand
    deactivate Model

    create CommandResult
    RemoveAssessmentCommand -> CommandResult
    activate CommandResult
    CommandResult --> RemoveAssessmentCommand
    deactivate CommandResult

    RemoveAssessmentCommand --> LogicManager : r
end

deactivate RemoveAssessmentCommand
[<-- LogicManager
deactivate LogicManager
@enduml
