@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":RemoveCourseCommandParser" as RemoveCourseCommandParser LOGIC_COLOR
participant "cmd:RemoveCourseCommand" as RemoveCourseCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("removecourse c/CS2103T")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("removecourse c/CS2103T")
activate AddressBookParser

create RemoveCourseCommandParser
AddressBookParser -> RemoveCourseCommandParser
activate RemoveCourseCommandParser

RemoveCourseCommandParser --> AddressBookParser
deactivate RemoveCourseCommandParser

AddressBookParser -> RemoveCourseCommandParser : parse(" c/CS2103T")
activate RemoveCourseCommandParser

create RemoveCourseCommand
RemoveCourseCommandParser -> RemoveCourseCommand
activate RemoveCourseCommand

RemoveCourseCommand --> RemoveCourseCommandParser
deactivate RemoveCourseCommand

RemoveCourseCommandParser --> AddressBookParser : cmd
deactivate RemoveCourseCommandParser

AddressBookParser --> LogicManager : cmd
deactivate AddressBookParser

LogicManager -> RemoveCourseCommand : execute(m)
activate RemoveCourseCommand

RemoveCourseCommand -> Model : hasCourse("CS2103T")
activate Model
Model --> RemoveCourseCommand : true
deactivate Model

alt course does not exist
    RemoveCourseCommand --> LogicManager : throws CommandException
else valid course code(s)
    RemoveCourseCommand -> Model : removeCourse(new Course("CS2103T"))
    activate Model
    Model --> RemoveCourseCommand
    deactivate Model

    create CommandResult
    RemoveCourseCommand -> CommandResult : CommandResult(successMessage)
    activate CommandResult
    CommandResult --> RemoveCourseCommand
    deactivate CommandResult

    RemoveCourseCommand --> LogicManager : r
end

deactivate RemoveCourseCommand
[<-- LogicManager
deactivate LogicManager
@enduml
