@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic as LogicPackage {

    package "Parser Classes" as ParserClasses {
        class AddressBookParser
        class XYZCommandParser
    }

    class XYZCommand
    class CommandResult
    class "{abstract}\nCommand" as Command

    class "<<interface>>\nLogic" as Logic
    class LogicManager
}

package Model {
    class HiddenModel #FFFFFF
}

package Storage {
    class HiddenStorage #FFFFFF
}

class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

LogicManager .right.|> Logic
LogicManager -left-> "1" AddressBookParser

AddressBookParser ..> XYZCommandParser : <<create>>
XYZCommandParser ..> XYZCommand : <<create>>

XYZCommand -up-|> Command
LogicManager .left.> Command : execute()

LogicManager --> "1" Model
LogicManager --> "1" Storage
Command .right.> Model

Logic ..> CommandResult
Command .up.> CommandResult : <<create>>

note right of XYZCommandParser
XYZCommandParser =
AddCourseCommandParser,
RemoveAssessmentCommandParser,
AddGradeCommandParser,
ListGradesCommandParser, etc
end note

note right of XYZCommand
XYZCommand =
AddCourseCommand,
RemoveAssessmentCommand,
AddGradeCommand,
ListGradesCommand, etc
end note
@enduml
