@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Class "{abstract}\nCommand" as Command
Class AddGradeCommand
Class AddStudentCommand
Class ListStudentsCommand

package "Parser classes"{
Class "<<interface>>\nParser" as Parser
Class AddressBookParser
Class AddGradeCommandParser
Class AddStudentCommandParser
Class ListStudentsCommandParser
Class CliSyntax
Class ParserUtil
Class ArgumentMultimap
Class ArgumentTokenizer
Class Prefix
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> AddressBookParser

AddressBookParser .down.> AddGradeCommandParser: <<create>>
AddressBookParser .down.> AddStudentCommandParser: <<create>>
AddressBookParser .down.> ListStudentsCommandParser: <<create>>

AddGradeCommandParser ..> AddGradeCommand : <<create>>
AddStudentCommandParser ..> AddStudentCommand : <<create>>
ListStudentsCommandParser ..> ListStudentsCommand : <<create>>

AddressBookParser ..> Command : <<use>>

AddGradeCommandParser .up.|> Parser
AddStudentCommandParser .up.|> Parser
ListStudentsCommandParser .up.|> Parser

AddGradeCommandParser ..> ArgumentMultimap
AddStudentCommandParser ..> ArgumentMultimap
ListStudentsCommandParser ..> ArgumentMultimap

ArgumentTokenizer .left.> ArgumentMultimap

AddGradeCommandParser ..> ArgumentTokenizer
AddStudentCommandParser ..> ArgumentTokenizer
ListStudentsCommandParser ..> ArgumentTokenizer

AddGradeCommandParser ..> CliSyntax
AddStudentCommandParser ..> CliSyntax
ListStudentsCommandParser ..> CliSyntax

CliSyntax ..> Prefix

AddGradeCommandParser ..> ParserUtil
AddStudentCommandParser ..> ParserUtil
ListStudentsCommandParser ..> ParserUtil

ParserUtil .down.> Prefix
ArgumentTokenizer .down.> Prefix

AddGradeCommand -up-|> Command
AddStudentCommand -up-|> Command
ListStudentsCommand -up-|> Command
@enduml
