@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

class "{abstract}\nCommand" as Command
class XYZCommand

package "Parser classes" {
    class "<<interface>>\nParser" as Parser
    class AddressBookParser
    class XYZCommandParser
    class CliSyntax
    class ParserUtil
    class ArgumentMultimap
    class ArgumentTokenizer
    class Prefix
}

class HiddenOutside #FFFFFF
HiddenOutside ..> AddressBookParser

AddressBookParser .down.> XYZCommandParser : <<create>>
AddressBookParser ..> Command : <<use>>

XYZCommandParser ..> XYZCommand : <<create>>
XYZCommandParser .up.|> Parser

XYZCommandParser ..> ArgumentMultimap
XYZCommandParser ..> ArgumentTokenizer
ArgumentTokenizer .left.> ArgumentMultimap

XYZCommandParser ..> CliSyntax
CliSyntax ..> Prefix

XYZCommandParser ..> ParserUtil
ParserUtil .down.> Prefix
ArgumentTokenizer .down.> Prefix

XYZCommand -up-|> Command

note right of XYZCommandParser
XYZCommandParser =
AddCourseCommandParser,
RemoveAssessmentCommandParser,
AddGradeCommandParser,
ListGradesCommandParser,
ListAssessmentsCommandParser, etc
end note

note right of XYZCommand
XYZCommand =
AddCourseCommand,
RemoveAssessmentCommand,
AddGradeCommand,
ListGradesCommand,
ListAssessmentsCommand, etc
end note
@enduml
